/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.search.web.internal.page;

import com.liferay.portal.configuration.metatype.bnd.util.ConfigurableUtil;
import com.liferay.portal.kernel.util.Portal;
import com.liferay.portal.search.web.configuration.DefaultSearchPageConfiguration;

import java.util.Map;

import org.osgi.service.component.annotations.Activate;
import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.Modified;
import org.osgi.service.component.annotations.Reference;

/**
 * @author André de Oliveira
 */
@Component(
	configurationPid = "com.liferay.portal.search.web.configuration.DefaultSearchPageConfiguration",
	immediate = true, service = DefaultSearchPageAutogenerator.class
)
public class DefaultSearchPageAutogenerator {

	public void generate(long companyId) throws Exception {
		if (!_autogenerateDefaultSearchPage) {
			return;
		}

		if (companyId != portal.getDefaultCompanyId()) {
			return;
		}

		defaultSearchPageGenerator.generate(companyId);
	}

	@Activate
	@Modified
	protected void activate(Map<String, Object> properties) {
		DefaultSearchPageConfiguration defaultSearchPageConfiguration =
			ConfigurableUtil.createConfigurable(
				DefaultSearchPageConfiguration.class, properties);

		setAutogenerateDefaultSearchPage(
			defaultSearchPageConfiguration.autogenerateDefaultSearchPage());
	}

	protected void setAutogenerateDefaultSearchPage(
		boolean autogenerateDefaultSearchPage) {

		_autogenerateDefaultSearchPage = autogenerateDefaultSearchPage;
	}

	@Reference
	protected DefaultSearchPageGenerator defaultSearchPageGenerator;

	@Reference
	protected Portal portal;

	private boolean _autogenerateDefaultSearchPage;

}