/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BackgroundTask service. Represents a row in the &quot;BackgroundTask&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portal.model.impl.BackgroundTaskModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portal.model.impl.BackgroundTaskImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BackgroundTask
 * @see com.liferay.portal.model.impl.BackgroundTaskImpl
 * @see com.liferay.portal.model.impl.BackgroundTaskModelImpl
 * @generated
 */
public interface BackgroundTaskModel extends BaseModel<BackgroundTask>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a background task model instance should use the {@link BackgroundTask} interface instead.
	 */

	/**
	 * Returns the primary key of this background task.
	 *
	 * @return the primary key of this background task
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this background task.
	 *
	 * @param primaryKey the primary key of this background task
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the background task ID of this background task.
	 *
	 * @return the background task ID of this background task
	 */
	public long getBackgroundTaskId();

	/**
	 * Sets the background task ID of this background task.
	 *
	 * @param backgroundTaskId the background task ID of this background task
	 */
	public void setBackgroundTaskId(long backgroundTaskId);

	/**
	 * Returns the group ID of this background task.
	 *
	 * @return the group ID of this background task
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this background task.
	 *
	 * @param groupId the group ID of this background task
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this background task.
	 *
	 * @return the company ID of this background task
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this background task.
	 *
	 * @param companyId the company ID of this background task
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this background task.
	 *
	 * @return the user ID of this background task
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this background task.
	 *
	 * @param userId the user ID of this background task
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this background task.
	 *
	 * @return the user uuid of this background task
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this background task.
	 *
	 * @param userUuid the user uuid of this background task
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this background task.
	 *
	 * @return the user name of this background task
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this background task.
	 *
	 * @param userName the user name of this background task
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this background task.
	 *
	 * @return the create date of this background task
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this background task.
	 *
	 * @param createDate the create date of this background task
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this background task.
	 *
	 * @return the modified date of this background task
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this background task.
	 *
	 * @param modifiedDate the modified date of this background task
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the class name of this background task.
	 *
	 * @return the class name of this background task
	 */
	@AutoEscape
	public String getClassName();

	/**
	 * Sets the class name of this background task.
	 *
	 * @param className the class name of this background task
	 */
	public void setClassName(String className);

	/**
	 * Returns the completed date of this background task.
	 *
	 * @return the completed date of this background task
	 */
	public Date getCompletedDate();

	/**
	 * Sets the completed date of this background task.
	 *
	 * @param completedDate the completed date of this background task
	 */
	public void setCompletedDate(Date completedDate);

	/**
	 * Returns the data of this background task.
	 *
	 * @return the data of this background task
	 */
	@AutoEscape
	public String getData();

	/**
	 * Sets the data of this background task.
	 *
	 * @param data the data of this background task
	 */
	public void setData(String data);

	/**
	 * Returns the name of this background task.
	 *
	 * @return the name of this background task
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this background task.
	 *
	 * @param name the name of this background task
	 */
	public void setName(String name);

	/**
	 * Returns the servlet context name of this background task.
	 *
	 * @return the servlet context name of this background task
	 */
	@AutoEscape
	public String getServletContextName();

	/**
	 * Sets the servlet context name of this background task.
	 *
	 * @param servletContextName the servlet context name of this background task
	 */
	public void setServletContextName(String servletContextName);

	/**
	 * Returns the status of this background task.
	 *
	 * @return the status of this background task
	 */
	public int getStatus();

	/**
	 * Sets the status of this background task.
	 *
	 * @param status the status of this background task
	 */
	public void setStatus(int status);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(BackgroundTask backgroundTask);

	public int hashCode();

	public CacheModel<BackgroundTask> toCacheModel();

	public BackgroundTask toEscapedModel();

	public BackgroundTask toUnescapedModel();

	public String toString();

	public String toXmlString();
}