/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.mobile.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.language.LanguageUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.HtmlUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.mobile.model.DeviceProfileAction;
import com.liferay.portal.mobile.model.DeviceProfileActionModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.Locale;
import java.util.Map;

/**
 * The base model implementation for the DeviceProfileAction service. Represents a row in the &quot;DeviceProfileAction&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.portal.mobile.model.DeviceProfileActionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DeviceProfileActionImpl}.
 * </p>
 *
 * @author Edward C. Han
 * @see DeviceProfileActionImpl
 * @see com.liferay.portal.mobile.model.DeviceProfileAction
 * @see com.liferay.portal.mobile.model.DeviceProfileActionModel
 * @generated
 */
public class DeviceProfileActionModelImpl extends BaseModelImpl<DeviceProfileAction>
	implements DeviceProfileActionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a device profile action model instance should use the {@link com.liferay.portal.mobile.model.DeviceProfileAction} interface instead.
	 */
	public static final String TABLE_NAME = "DeviceProfileAction";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "deviceProfileActionId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "deviceProfileId", Types.BIGINT },
			{ "deviceProfileRuleId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "type_", Types.VARCHAR },
			{ "typeSettings", Types.CLOB }
		};
	public static final String TABLE_SQL_CREATE = "create table DeviceProfileAction (uuid_ VARCHAR(75) null,deviceProfileActionId LONG not null primary key,groupId LONG,deviceProfileId LONG,deviceProfileRuleId LONG,name STRING null,description STRING null,type_ VARCHAR(255) null,typeSettings TEXT null)";
	public static final String TABLE_SQL_DROP = "drop table DeviceProfileAction";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.liferay.portal.mobile.model.DeviceProfileAction"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.liferay.portal.mobile.model.DeviceProfileAction"),
			true);

	public Class<?> getModelClass() {
		return DeviceProfileAction.class;
	}

	public String getModelClassName() {
		return DeviceProfileAction.class.getName();
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.portal.util.PropsUtil.get(
				"lock.expiration.time.com.liferay.portal.mobile.model.DeviceProfileAction"));

	public DeviceProfileActionModelImpl() {
	}

	public long getPrimaryKey() {
		return _deviceProfileActionId;
	}

	public void setPrimaryKey(long primaryKey) {
		setDeviceProfileActionId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_deviceProfileActionId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	public long getDeviceProfileActionId() {
		return _deviceProfileActionId;
	}

	public void setDeviceProfileActionId(long deviceProfileActionId) {
		_deviceProfileActionId = deviceProfileActionId;
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	public long getDeviceProfileId() {
		return _deviceProfileId;
	}

	public void setDeviceProfileId(long deviceProfileId) {
		_deviceProfileId = deviceProfileId;
	}

	public long getDeviceProfileRuleId() {
		return _deviceProfileRuleId;
	}

	public void setDeviceProfileRuleId(long deviceProfileRuleId) {
		_deviceProfileRuleId = deviceProfileRuleId;
	}

	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public String getName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId);
	}

	public String getName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId, useDefault);
	}

	public String getName(String languageId) {
		String value = LocalizationUtil.getLocalization(getName(), languageId);

		if (isEscapedModel()) {
			return HtmlUtil.escape(value);
		}
		else {
			return value;
		}
	}

	public String getName(String languageId, boolean useDefault) {
		String value = LocalizationUtil.getLocalization(getName(), languageId,
				useDefault);

		if (isEscapedModel()) {
			return HtmlUtil.escape(value);
		}
		else {
			return value;
		}
	}

	public Map<Locale, String> getNameMap() {
		return LocalizationUtil.getLocalizationMap(getName());
	}

	public void setName(String name) {
		_name = name;
	}

	public void setName(String name, Locale locale) {
		setName(name, locale, LocaleUtil.getDefault());
	}

	public void setName(String name, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(name)) {
			setName(LocalizationUtil.updateLocalization(getName(), "Name",
					name, languageId, defaultLanguageId));
		}
		else {
			setName(LocalizationUtil.removeLocalization(getName(), "Name",
					languageId));
		}
	}

	public void setNameMap(Map<Locale, String> nameMap) {
		setNameMap(nameMap, LocaleUtil.getDefault());
	}

	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale) {
		if (nameMap == null) {
			return;
		}

		Locale[] locales = LanguageUtil.getAvailableLocales();

		for (Locale locale : locales) {
			String name = nameMap.get(locale);

			setName(name, locale, defaultLocale);
		}
	}

	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	public String getDescription(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId);
	}

	public String getDescription(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId, useDefault);
	}

	public String getDescription(String languageId) {
		String value = LocalizationUtil.getLocalization(getDescription(),
				languageId);

		if (isEscapedModel()) {
			return HtmlUtil.escape(value);
		}
		else {
			return value;
		}
	}

	public String getDescription(String languageId, boolean useDefault) {
		String value = LocalizationUtil.getLocalization(getDescription(),
				languageId, useDefault);

		if (isEscapedModel()) {
			return HtmlUtil.escape(value);
		}
		else {
			return value;
		}
	}

	public Map<Locale, String> getDescriptionMap() {
		return LocalizationUtil.getLocalizationMap(getDescription());
	}

	public void setDescription(String description) {
		_description = description;
	}

	public void setDescription(String description, Locale locale) {
		setDescription(description, locale, LocaleUtil.getDefault());
	}

	public void setDescription(String description, Locale locale,
		Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(description)) {
			setDescription(LocalizationUtil.updateLocalization(
					getDescription(), "Description", description, languageId,
					defaultLanguageId));
		}
		else {
			setDescription(LocalizationUtil.removeLocalization(
					getDescription(), "Description", languageId));
		}
	}

	public void setDescriptionMap(Map<Locale, String> descriptionMap) {
		setDescriptionMap(descriptionMap, LocaleUtil.getDefault());
	}

	public void setDescriptionMap(Map<Locale, String> descriptionMap,
		Locale defaultLocale) {
		if (descriptionMap == null) {
			return;
		}

		Locale[] locales = LanguageUtil.getAvailableLocales();

		for (Locale locale : locales) {
			String description = descriptionMap.get(locale);

			setDescription(description, locale, defaultLocale);
		}
	}

	public String getType() {
		if (_type == null) {
			return StringPool.BLANK;
		}
		else {
			return _type;
		}
	}

	public void setType(String type) {
		_type = type;
	}

	public String getTypeSettings() {
		if (_typeSettings == null) {
			return StringPool.BLANK;
		}
		else {
			return _typeSettings;
		}
	}

	public void setTypeSettings(String typeSettings) {
		_typeSettings = typeSettings;
	}

	@Override
	public DeviceProfileAction toEscapedModel() {
		if (isEscapedModel()) {
			return (DeviceProfileAction)this;
		}
		else {
			if (_escapedModelProxy == null) {
				_escapedModelProxy = (DeviceProfileAction)Proxy.newProxyInstance(_classLoader,
						_escapedModelProxyInterfaces,
						new AutoEscapeBeanHandler(this));
			}

			return _escapedModelProxy;
		}
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					DeviceProfileAction.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		DeviceProfileActionImpl deviceProfileActionImpl = new DeviceProfileActionImpl();

		deviceProfileActionImpl.setUuid(getUuid());
		deviceProfileActionImpl.setDeviceProfileActionId(getDeviceProfileActionId());
		deviceProfileActionImpl.setGroupId(getGroupId());
		deviceProfileActionImpl.setDeviceProfileId(getDeviceProfileId());
		deviceProfileActionImpl.setDeviceProfileRuleId(getDeviceProfileRuleId());
		deviceProfileActionImpl.setName(getName());
		deviceProfileActionImpl.setDescription(getDescription());
		deviceProfileActionImpl.setType(getType());
		deviceProfileActionImpl.setTypeSettings(getTypeSettings());

		deviceProfileActionImpl.resetOriginalValues();

		return deviceProfileActionImpl;
	}

	public int compareTo(DeviceProfileAction deviceProfileAction) {
		long primaryKey = deviceProfileAction.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		DeviceProfileAction deviceProfileAction = null;

		try {
			deviceProfileAction = (DeviceProfileAction)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = deviceProfileAction.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DeviceProfileActionModelImpl deviceProfileActionModelImpl = this;

		deviceProfileActionModelImpl._originalUuid = deviceProfileActionModelImpl._uuid;

		deviceProfileActionModelImpl._originalGroupId = deviceProfileActionModelImpl._groupId;

		deviceProfileActionModelImpl._setOriginalGroupId = false;
	}

	@Override
	public CacheModel<DeviceProfileAction> toCacheModel() {
		DeviceProfileActionCacheModel deviceProfileActionCacheModel = new DeviceProfileActionCacheModel();

		deviceProfileActionCacheModel.uuid = getUuid();

		String uuid = deviceProfileActionCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			deviceProfileActionCacheModel.uuid = null;
		}

		deviceProfileActionCacheModel.deviceProfileActionId = getDeviceProfileActionId();

		deviceProfileActionCacheModel.groupId = getGroupId();

		deviceProfileActionCacheModel.deviceProfileId = getDeviceProfileId();

		deviceProfileActionCacheModel.deviceProfileRuleId = getDeviceProfileRuleId();

		deviceProfileActionCacheModel.name = getName();

		String name = deviceProfileActionCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			deviceProfileActionCacheModel.name = null;
		}

		deviceProfileActionCacheModel.description = getDescription();

		String description = deviceProfileActionCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			deviceProfileActionCacheModel.description = null;
		}

		deviceProfileActionCacheModel.type = getType();

		String type = deviceProfileActionCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			deviceProfileActionCacheModel.type = null;
		}

		deviceProfileActionCacheModel.typeSettings = getTypeSettings();

		String typeSettings = deviceProfileActionCacheModel.typeSettings;

		if ((typeSettings != null) && (typeSettings.length() == 0)) {
			deviceProfileActionCacheModel.typeSettings = null;
		}

		return deviceProfileActionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", deviceProfileActionId=");
		sb.append(getDeviceProfileActionId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", deviceProfileId=");
		sb.append(getDeviceProfileId());
		sb.append(", deviceProfileRuleId=");
		sb.append(getDeviceProfileRuleId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", typeSettings=");
		sb.append(getTypeSettings());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.liferay.portal.mobile.model.DeviceProfileAction");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deviceProfileActionId</column-name><column-value><![CDATA[");
		sb.append(getDeviceProfileActionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deviceProfileId</column-name><column-value><![CDATA[");
		sb.append(getDeviceProfileId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deviceProfileRuleId</column-name><column-value><![CDATA[");
		sb.append(getDeviceProfileRuleId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>typeSettings</column-name><column-value><![CDATA[");
		sb.append(getTypeSettings());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DeviceProfileAction.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			DeviceProfileAction.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _deviceProfileActionId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _deviceProfileId;
	private long _deviceProfileRuleId;
	private String _name;
	private String _description;
	private String _type;
	private String _typeSettings;
	private transient ExpandoBridge _expandoBridge;
	private DeviceProfileAction _escapedModelProxy;
}