/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.mobile.model.impl;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.mobile.model.DeviceProfileRule;
import com.liferay.portal.mobile.service.DeviceProfileRuleLocalServiceUtil;

/**
 * The extended model base implementation for the DeviceProfileRule service. Represents a row in the &quot;DeviceProfileRule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DeviceProfileRuleImpl}.
 * </p>
 *
 * @author Edward C. Han
 * @see DeviceProfileRuleImpl
 * @see com.liferay.portal.mobile.model.DeviceProfileRule
 * @generated
 */
public abstract class DeviceProfileRuleBaseImpl
	extends DeviceProfileRuleModelImpl implements DeviceProfileRule {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a device profile rule model instance should use the {@link DeviceProfileRule} interface instead.
	 */
	public void save() throws SystemException {
		DeviceProfileRuleLocalServiceUtil.updateDeviceProfileRule(this);
	}
}